apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aid7qeqtk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aid7qeqtk-go 
  name: aid7qeqtk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aid7qeqtk-go 
